ALTER TABLE accounts ADD COLUMN proxy_status VARCHAR DEFAULT 'unknown';
ALTER TABLE accounts ADD COLUMN proxy_ip VARCHAR;
ALTER TABLE accounts ADD COLUMN proxy_latency FLOAT;
ALTER TABLE accounts ADD COLUMN proxy_last_checked DATETIME;
ALTER TABLE accounts ADD COLUMN proxy_last_error TEXT;
ALTER TABLE accounts ADD COLUMN proxy_failures INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN session_status VARCHAR DEFAULT 'expired';
ALTER TABLE accounts ADD COLUMN session_last_checked DATETIME;
ALTER TABLE accounts ADD COLUMN session_last_error TEXT;
ALTER TABLE accounts ADD COLUMN session_auth_failures INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN session_captcha_triggers INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN worker_job_id VARCHAR;
ALTER TABLE accounts ADD COLUMN worker_started_at DATETIME;
ALTER TABLE accounts ADD COLUMN worker_error TEXT;
ALTER TABLE accounts ADD COLUMN worker_last_completed_at DATETIME;
ALTER TABLE accounts ADD COLUMN retry_count INTEGER DEFAULT 0;
ALTER TABLE accounts ADD COLUMN retry_limit INTEGER DEFAULT 3;
ALTER TABLE accounts ADD COLUMN retry_reason TEXT;
ALTER TABLE accounts ADD COLUMN retry_next_at DATETIME;
ALTER TABLE accounts ADD COLUMN last_exception TEXT;
ALTER TABLE accounts ADD COLUMN permanently_failed BOOLEAN DEFAULT 0;
ALTER TABLE accounts ADD COLUMN messages_sent_reset_at DATETIME;
