INITIAL_MESSAGE_SENT = "INITIAL_MESSAGE_SENT"
NEW_REPLY = "NEW_REPLY"
AI_REPLIED = "AI_REPLIED"
PHONE_ACQUIRED = "PHONE_ACQUIRED"
AI_FAILED = "AI_FAILED"
REPLY_DISABLED = "REPLY_DISABLED"
AGENT_SKIPPED = "AGENT_SKIPPED"
SKIPPED = "SKIPPED"
DUPLICATE_LEAD = "DUPLICATE_LEAD"
NEW_LEAD = "NEW_LEAD"

VIEWING_DISCUSSION = (
    "VIEWING_DISCUSSION"
)

VIEWING_PENDING = "VIEWING_PENDING"

VIEWING_BOOKED = (
    "VIEWING_BOOKED"
)

PRE_VIEWING = (
    "PRE_VIEWING"
)

CONTACT_REQUESTED = (
    "CONTACT_REQUESTED"
)

VIEWING_CANCELLED = (
    "VIEWING_CANCELLED"
)

HANDOFF_COMPLETE = (
    "HANDOFF_COMPLETE"
)

CLOSED = "CLOSED"
