/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchProfilesRouteImport } from './routes/search-profiles'
import { Route as ProxiesRouteImport } from './routes/proxies'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as FailedAccountsRouteImport } from './routes/failed-accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsThreadIdRouteImport } from './routes/leads.$threadId'

const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const FailedAccountsRoute = FailedAccountsRouteImport.update({
  id: '/failed-accounts',
  path: '/failed-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxiesRoute = ProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchProfilesRoute = SearchProfilesRouteImport.update({
  id: '/search-profiles',
  path: '/search-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsThreadIdRoute = LeadsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => LeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/workers': typeof WorkersRoute
  '/leads': typeof LeadsRouteWithChildren
  '/logs': typeof LogsRoute
  '/login': typeof LoginRoute
  '/proxies': typeof ProxiesRoute
  '/search-profiles': typeof SearchProfilesRoute
  '/settings': typeof SettingsRoute
  '/locations': typeof LocationsRoute
  '/failed-accounts': typeof FailedAccountsRoute
  '/leads/$threadId': typeof LeadsThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/workers': typeof WorkersRoute
  '/leads': typeof LeadsRouteWithChildren
  '/logs': typeof LogsRoute
  '/login': typeof LoginRoute
  '/proxies': typeof ProxiesRoute
  '/search-profiles': typeof SearchProfilesRoute
  '/settings': typeof SettingsRoute
  '/locations': typeof LocationsRoute
  '/failed-accounts': typeof FailedAccountsRoute
  '/leads/$threadId': typeof LeadsThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/workers': typeof WorkersRoute
  '/leads': typeof LeadsRouteWithChildren
  '/logs': typeof LogsRoute
  '/login': typeof LoginRoute
  '/proxies': typeof ProxiesRoute
  '/search-profiles': typeof SearchProfilesRoute
  '/settings': typeof SettingsRoute
  '/locations': typeof LocationsRoute
  '/failed-accounts': typeof FailedAccountsRoute
  '/leads/$threadId': typeof LeadsThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/workers'
    | '/leads'
    | '/logs'
    | '/login'
    | '/proxies'
    | '/search-profiles'
    | '/settings'
    | '/locations'
    | '/failed-accounts'
    | '/leads/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/workers'
    | '/leads'
    | '/logs'
    | '/login'
    | '/proxies'
    | '/search-profiles'
    | '/settings'
    | '/locations'
    | '/failed-accounts'
    | '/leads/$threadId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/workers'
    | '/leads'
    | '/logs'
    | '/login'
    | '/proxies'
    | '/search-profiles'
    | '/settings'
    | '/locations'
    | '/failed-accounts'
    | '/leads/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  WorkersRoute: typeof WorkersRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LogsRoute: typeof LogsRoute
  LoginRoute: typeof LoginRoute
  ProxiesRoute: typeof ProxiesRoute
  SearchProfilesRoute: typeof SearchProfilesRoute
  SettingsRoute: typeof SettingsRoute
  LocationsRoute: typeof LocationsRoute
  FailedAccountsRoute: typeof FailedAccountsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxies': {
      id: '/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof ProxiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-profiles': {
      id: '/search-profiles'
      path: '/search-profiles'
      fullPath: '/search-profiles'
      preLoaderRoute: typeof SearchProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failed-accounts': {
      id: '/failed-accounts'
      path: '/failed-accounts'
      fullPath: '/failed-accounts'
      preLoaderRoute: typeof FailedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$threadId': {
      id: '/leads/$threadId'
      path: '/$threadId'
      fullPath: '/leads/$threadId'
      preLoaderRoute: typeof LeadsThreadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
  }
}

interface LeadsRouteChildren {
  LeadsThreadIdRoute: typeof LeadsThreadIdRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsThreadIdRoute: LeadsThreadIdRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  WorkersRoute: WorkersRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LogsRoute: LogsRoute,
  LoginRoute: LoginRoute,
  ProxiesRoute: ProxiesRoute,
  SearchProfilesRoute: SearchProfilesRoute,
  SettingsRoute: SettingsRoute,
  LocationsRoute: LocationsRoute,
  FailedAccountsRoute: FailedAccountsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
