import math

from app.openrent.popups import close_verified_tenant_popup
from app.utils.human import random_sleep
from app.utils.logger import logger
import re
from playwright.async_api import TimeoutError as PlaywrightTimeoutError


BASE_URL = "https://www.openrent.co.uk/myenquiries"


async def open_inbox_page(page, start=0):

    url = f"{BASE_URL}?Start={start}"

    print(f"\nOpening inbox page: {url}")

    await page.goto(url, wait_until="domcontentloaded", timeout=30_000)

    await page.wait_for_load_state("load")


async def get_total_pages(page):

    try:

        paragraphs = await page.query_selector_all("p")

        for p in paragraphs:

            text = await p.inner_text()

            text = text.strip()

            print("Paragraph text:", text)

            # Example:
            # Page:
            # 6 / 7

            if "Page:" in text and "/" in text:

                parts = text.split("/")

                total = parts[-1].strip()

                return int(total)

        return 1

    except Exception as e:

        print("Could not detect total pages:", e)

        return 1

async def extract_reply_threads(page):

    cards = await page.query_selector_all(
        "div[id^='thread-']"
    )

    results = []

    print(f"Found {len(cards)} thread cards")

    for card in cards:

        try:

            thread_id = await card.get_attribute("id")

            if not thread_id:
                continue

            thread_id = thread_id.replace("thread-", "")

            # Find preview text
            preview = await card.query_selector(
                "p.text-secondary"
            )

            if not preview:
                continue

            preview_text = (
                await preview.inner_text()
            ).strip()

            print(
                f"Thread {thread_id} "
                f"preview: {preview_text}"
            )

            # Skip our own messages
            if preview_text.lower().startswith("you:"):
                continue

            results.append({
                "thread_id": thread_id,
                "preview": preview_text
            })

        except Exception as e:

            print("Failed parsing thread:", e)

    return results


async def get_all_reply_threads(page):

    all_threads = []

    processed = set()

    # Open first page
    await open_inbox_page(page, start=0)

    total_pages = await get_total_pages(page)

    print(f"\nTotal inbox pages: {total_pages}\n")

    threads = await extract_reply_threads(page)

    for thread in threads:

        thread_id = thread["thread_id"]

        if thread_id in processed:
            continue

        processed.add(thread_id)

        all_threads.append(thread)

    await random_sleep(2, 5)

    for page_num in range(1, total_pages):

        start = page_num * 10

        await open_inbox_page(page, start=start)

        threads = await extract_reply_threads(page)

        for thread in threads:

            thread_id = thread["thread_id"]

            if thread_id in processed:
                continue

            processed.add(thread_id)

            all_threads.append(thread)
        await random_sleep(2, 5)

    return all_threads

async def open_thread(page, thread_id):

    url = (
        f"https://www.openrent.co.uk/messages/"
        f"{thread_id}"
    )

    print(f"\nOpening thread: {url}")

    await page.goto(url, wait_until="domcontentloaded", timeout=30_000)

    await page.wait_for_load_state("load")
    logger.info("THREAD PAGE LOAD COMPLETE")
    print("THREAD PAGE LOAD COMPLETE")
    await close_verified_tenant_popup(page)
    await page.wait_for_selector(".message-content", timeout=15_000)
    logger.info("THREAD ELEMENT DETECTED")
    print("THREAD ELEMENT DETECTED")
    await close_verified_tenant_popup(page)

async def extract_conversation(page):

    await close_verified_tenant_popup(page)

    messages = await page.query_selector_all(
        ".message-content"
    )

    results = []

    for msg in messages:

        try:

            text = await msg.inner_text()

            text = text.strip()

            if not text:
                continue

            # Skip OpenRent auto messages
            classes = await msg.get_attribute("class")

            if not classes:
                classes = ""

            # Detect sender
            sender = "landlord"

            if "current-user" in classes:
                sender = "us"

            # Skip autogenerated OpenRent messages
            if "autogenerated-message" in classes:
                continue

            timestamp = await msg.get_attribute(
                "data-message-time"
            )

            results.append({
                "sender": sender,
                "message": text,
                "timestamp": timestamp
            })

        except Exception as e:

            print("Failed parsing message:", e)

    return results

def should_ai_reply(messages):

    if not messages:
        return False

    latest = messages[-1]

    # Only reply if landlord spoke last
    return latest["sender"] == "landlord"

def get_landlord_messages(messages):

    landlord_messages = []

    for msg in messages:

        if msg["sender"] != "landlord":
            continue

        landlord_messages.append(
            msg["message"]
        )

    return landlord_messages

async def send_reply(
    page,
    reply_text
):

    await close_verified_tenant_popup(page)

    textarea = page.locator(
        "#message-compose-textarea"
    )

    try:
        await textarea.wait_for(timeout=15_000)
    except PlaywrightTimeoutError:
        logger.warning("send_reply: reply textarea not found (session expired or page failed to load)")
        return False

    # Check disabled state
    disabled = await textarea.get_attribute(
        "disabled"
    )

    if disabled is not None:

        print(
            "\nReply box disabled. "
            "Skipping thread."
        )

        return False

    # Click textarea
    await close_verified_tenant_popup(page)
    await textarea.click()

    # Type naturally
    await textarea.type(
        reply_text,
        delay=30
    )

    print("\nAI reply inserted")

    await page.wait_for_timeout(1500)

    submit_button = page.locator(
        "#send-message-button"
    )

    # Verify button enabled
    button_disabled = await submit_button.get_attribute(
        "disabled"
    )

    if button_disabled is not None:

        print(
            "Send button disabled. "
            "Skipping send."
        )

        return False

    await close_verified_tenant_popup(page)
    await submit_button.click()

    print("AI reply sent")

    return True

async def can_reply(page):

    await close_verified_tenant_popup(page)

    textarea = page.locator(
        "#message-compose-textarea"
    )

    try:
        await textarea.wait_for(timeout=15_000)
    except PlaywrightTimeoutError:
        logger.warning("can_reply: reply textarea not found (session expired or page failed to load)")
        return False

    disabled = await textarea.get_attribute(
        "disabled"
    )

    return disabled is None

def get_latest_landlord_message(
    messages
):

    landlord_messages = [

        msg["message"]

        for msg in messages

        if msg["sender"] == "landlord"
    ]

    if not landlord_messages:
        return None

    return landlord_messages[-1]

async def reveal_hidden_phone_number(page):
    try:

        await close_verified_tenant_popup(page)

        # Find reveal link inside message thread
        reveal_link = page.locator(
            "a:has-text('Click here to reveal the contact information now')"
        )

        if await reveal_link.count() == 0:
            return False

        print("\nHidden contact link found")
        
        await reveal_link.first.click()

        # Wait for popup/modal
        modal_button = page.locator(
            "button:has-text('Proceed: I understand the risks')"
        )

        await modal_button.wait_for(timeout=5000)

        print("Risk popup detected")

        await modal_button.click()

        # Wait for number/message to refresh
        await page.wait_for_timeout(3000)

        print("Contact information revealed")

        return True

    except PlaywrightTimeoutError:
        print("Reveal popup timeout")
        return False

    except Exception as e:
        print(f"Failed revealing contact info: {e}")
        return False
