import math
import re


BASE_URL = "https://www.openrent.co.uk/myenquiries"


async def open_inbox_page(page, start=0):

    url = f"{BASE_URL}?Start={start}"

    print(f"\nOpening inbox page: {url}")

    await page.goto(url)

    await page.wait_for_load_state("networkidle")


async def get_total_pages(page):

    try:

        paragraphs = await page.query_selector_all("p")

        for p in paragraphs:

            text = await p.inner_text()

            text = text.strip()

            print("Paragraph text:", text)

            # Example:
            # Page:
            # 6 / 7

            if "Page:" in text and "/" in text:

                parts = text.split("/")

                total = parts[-1].strip()

                return int(total)

        return 1

    except Exception as e:

        print("Could not detect total pages:", e)

        return 1

async def extract_reply_threads(page):

    cards = await page.query_selector_all(
        "div[id^='thread-']"
    )

    results = []

    print(f"Found {len(cards)} thread cards")

    for card in cards:

        try:

            thread_id = await card.get_attribute("id")

            if not thread_id:
                continue

            thread_id = thread_id.replace("thread-", "")

            # Find preview text
            preview = await card.query_selector(
                "p.text-secondary"
            )

            if not preview:
                continue

            preview_text = (
                await preview.inner_text()
            ).strip()

            print(
                f"Thread {thread_id} "
                f"preview: {preview_text}"
            )

            # Skip our own messages
            if preview_text.lower().startswith("you:"):
                continue

            results.append({
                "thread_id": thread_id,
                "preview": preview_text
            })

        except Exception as e:

            print("Failed parsing thread:", e)

    return results


async def get_all_reply_threads(page):

    all_threads = []

    processed = set()

    # Open first page
    await open_inbox_page(page, start=0)

    total_pages = await get_total_pages(page)

    print(f"\nTotal inbox pages: {total_pages}\n")

    for page_num in range(total_pages):

        start = page_num * 10

        await open_inbox_page(page, start=start)

        threads = await extract_reply_threads(page)

        for thread in threads:

            thread_id = thread["thread_id"]

            if thread_id in processed:
                continue

            processed.add(thread_id)

            all_threads.append(thread)

    return all_threads

async def open_thread(page, thread_id):

    url = (
        f"https://www.openrent.co.uk/messages/"
        f"{thread_id}"
    )

    print(f"\nOpening thread: {url}")

    await page.goto(url)

    await page.wait_for_load_state("networkidle")

async def extract_conversation(page):

    messages = await page.query_selector_all(
        ".message-content"
    )

    results = []

    for msg in messages:

        try:

            text = await msg.inner_text()

            text = text.strip()

            if not text:
                continue

            # Skip OpenRent auto messages
            classes = await msg.get_attribute("class")

            if not classes:
                classes = ""

            # Detect sender
            sender = "landlord"

            if "current-user" in classes:
                sender = "us"

            # Skip autogenerated OpenRent messages
            if "autogenerated-message" in classes:
                continue

            timestamp = await msg.get_attribute(
                "data-message-time"
            )

            results.append({
                "sender": sender,
                "message": text,
                "timestamp": timestamp
            })

        except Exception as e:

            print("Failed parsing message:", e)

    return results



def extract_phone_number(messages):

    combined_text = "\n".join(
        msg["message"]
        for msg in messages
    )

    # Remove spaces and symbols for detection
    cleaned = re.sub(r"[^\d+]", "", combined_text)

    # UK phone detection
    patterns = [

        r"(\+44\d{10,12})",

        r"(07\d{9})",

        r"(447\d{9})"
    ]

    for pattern in patterns:

        match = re.search(pattern, cleaned)

        if match:
            return match.group(1)

    return None

def should_ai_reply(messages):

    if not messages:
        return False

    latest = messages[-1]

    # Only reply if landlord spoke last
    return latest["sender"] == "landlord"

def get_landlord_messages(messages):

    landlord_messages = []

    for msg in messages:

        if msg["sender"] != "landlord":
            continue

        landlord_messages.append(
            msg["message"]
        )

    return landlord_messages

async def send_reply(
    page,
    reply_text
):

    textarea = page.locator(
        "#message-compose-textarea"
    )

    await textarea.wait_for()

    # Check disabled state
    disabled = await textarea.get_attribute(
        "disabled"
    )

    if disabled is not None:

        print(
            "\nReply box disabled. "
            "Skipping thread."
        )

        return False

    # Click textarea
    await textarea.click()

    # Type naturally
    await textarea.type(
        reply_text,
        delay=30
    )

    print("\nAI reply inserted")

    await page.wait_for_timeout(1500)

    submit_button = page.locator(
        "#send-message-button"
    )

    # Verify button enabled
    button_disabled = await submit_button.get_attribute(
        "disabled"
    )

    if button_disabled is not None:

        print(
            "Send button disabled. "
            "Skipping send."
        )

        return False

    # TEST MODE
    # await submit_button.click()

    print("AI reply ready")

    return True

async def can_reply(page):

    textarea = page.locator(
        "#message-compose-textarea"
    )

    await textarea.wait_for()

    disabled = await textarea.get_attribute(
        "disabled"
    )

    return disabled is None

def get_latest_landlord_message(
    messages
):

    landlord_messages = [

        msg["message"]

        for msg in messages

        if msg["sender"] == "landlord"
    ]

    if not landlord_messages:
        return None

    return landlord_messages[-1]